# Generated by Django 3.2.8 on 2022-04-22 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('search_start', models.DateField()),
                ('adress', models.CharField(max_length=100)),
                ('facility', models.ManyToManyField(blank=True, related_name='event_facility', to=settings.AUTH_USER_MODEL)),
                ('head', models.ManyToManyField(blank=True, related_name='event_head', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='event_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
