# Generated by Django 3.2.8 on 2022-04-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220422_0723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Operation',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='operations',
            field=models.ManyToManyField(blank=True, related_name='user_operations', to='main.Operation'),
        ),
    ]
