# Generated by Django 3.2.8 on 2022-04-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_volunteer_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(default='Не найден(-а)', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operation'),
        ),
    ]
