# Generated by Django 3.2.8 on 2022-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220422_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='facility',
            field=models.ManyToManyField(blank=True, related_name='event_facility', to='main.Facility'),
        ),
    ]
