# Generated by Django 3.2.8 on 2022-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_operation_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='coord',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='plan',
            field=models.TextField(default=''),
        ),
    ]
