# Generated by Django 3.2.8 on 2022-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220422_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='coord',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
