# Generated by Django 3.2.8 on 2022-04-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_operation_coord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='coord',
            new_name='coords',
        ),
    ]
