# Generated by Django 3.2.8 on 2022-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_coord_operation_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(default='Не найден', max_length=50),
        ),
    ]
