# Generated by Django 3.2.8 on 2022-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_operation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
