# Generated by Django 3.2.8 on 2022-04-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220423_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='event_volunteers', to='main.Volunteer'),
        ),
    ]
