# Generated by Django 3.2.8 on 2022-04-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220423_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_start', models.DateField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='user_events', to='main.Event'),
        ),
    ]
