# Generated by Django 3.2.8 on 2022-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220423_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
