# Generated by Django 3.2.8 on 2022-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='tg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
