# Generated by Django 3.2.8 on 2022-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220423_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
