# Generated by Django 3.2.8 on 2022-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_operation_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='appearance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
