# Generated by Django 3.2.8 on 2022-04-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_operation_appearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='operation',
            name='search_start',
            field=models.CharField(default='', max_length=20),
        ),
    ]
